### ISSUE TITLE
2,4 WLAN dont work

### ISSUE THREAD

**Issue by hipposen** [zuzia-dev/Easybox-904xDSL-repo-source#1]
i ran in the issue that the wifi dont work, it always say wrong password.

**Comment by hipposen** [comment]
i think it has something to do how the vlans of the wifi devices are connected.

**Comment by Meierhans2** [comment]
Wifi worked for me without any problems on all firmware versions I tried. Make sure to configure via config files, not via Luci. Run /etc/wifi-on after doing changes there.

I think this issue can be closed.

**Comment by zuzia-dev** [comment]
The problem with vlans and 2.4 GHz Wi-Fi has been resolved in ver.2.
VPE: https://github.com/zuzia-dev/Easybox-904xDSL-repo-source/blob/main/Firmware/VPE/v2/openwrt-lantiq-xrx200-arcadyan_vgv952cjw33-e-ir-vpe-squashfs-sysupgrade.bin
SMP: https://github.com/zuzia-dev/Easybox-904xDSL-repo-source/blob/main/Firmware/SMP/v2/openwrt-lantiq-xrx200-arcadyan_vgv952cjw33-e-ir-smp-squashfs-sysupgrade.bin
