### ISSUE TITLE
Router gets stuck easily into recovery mode without  hacked bootloader

### ISSUE THREAD

**Issue by Meierhans2** [zuzia-dev/Easybox-904xDSL-repo-source#2]
Newer firmware versions (>115 afaik)
tend to trigger the "redscreen of death" on simple changes very often. Installing the hacked uboot fixed this issue for me.

Maybe installing it should be made mandatory in the tutorials?

**Comment by zuzia-dev** [comment]
Hi @Meierhans2 
Thank you for your advice, I added to the description a reference to the installation of this version of the bootloader.
